"""empty message

Revision ID: 605263d03623
Revises: cae8e35c91c5
Create Date: 2021-11-13 18:02:00.332820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605263d03623'
down_revision = 'cae8e35c91c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_reference', sa.String(length=5), nullable=True),
    sa.Column('order_firstname', sa.String(length=20), nullable=True),
    sa.Column('order_lastname', sa.String(length=20), nullable=True),
    sa.Column('order_phone', sa.Integer(), nullable=True),
    sa.Column('order_email', sa.String(length=50), nullable=True),
    sa.Column('order_address', sa.String(length=100), nullable=True),
    sa.Column('order_city', sa.String(length=100), nullable=True),
    sa.Column('order_zip', sa.String(length=20), nullable=True),
    sa.Column('order_status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('order__item',
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menu_item.menu_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order__item')
    op.drop_table('order')
    # ### end Alembic commands ###
